name: Deploy JSON to GitHub Pages

on:
  push:
    branches:
      - mogai-auto
      - mogai
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4  # Updated to v4

      - name: Prepare artifact
        run: |
          mkdir -p output
          cp converted_data.json converted_data_intl.json output/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3  # Updated to v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Updated to v4