name: Deploy JSON to GitHub Pages

on:
  push:
    branches:
      - mogai-auto
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # 1. 签出代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. 配置 Pages 环境
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 3. 准备要发布的文件
      - name: Prepare artifact
        run: |
          mkdir -p output
          cp converted_data.json converted_data_intl.json output/
          # 如果想同时发布一个格式化页面，取消下面注释：
          # cat > output/index.html << 'EOF'
          # <!DOCTYPE html>
          # <html lang="zh-CN">
          # <head><meta charset="UTF-8"><title>JSON Viewer</title></head>
          # <body><pre id="data">Loading…</pre>
          # <script>
          #   fetch('converted_data.json')
          #     .then(r => r.json())
          #     .then(d=>document.getElementById('data').textContent=JSON.stringify(d,null,2))
          #     .catch(e=>document.getElementById('data').textContent=e);
          # </script>
          # </body>
          # </html>
          # EOF

      # 4. 上传给 Pages 用的 artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

      # 5. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
