name: Deploy JSON to GitHub Pages

# 只在 mogai-auto 分支有推送时触发
on:
  push:
    branches:
      - mogai-auto

jobs:
  deploy:
    runs-on: ubuntu-latest

    # 给 Pages 所需的权限
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # 1. 签出代码（完整历史，以防需要切分大文件）
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. 初始化 Pages 环境
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 3. 准备要发布的文件
      - name: Prepare artifact
        run: |
          mkdir -p output
          # 复制两个 JSON 到发布目录
          cp converted_data.json converted_data_intl.json output/
          # 如果你想加一个格式化展示页面，可以取消下面几行的注释：
          # cat > output/index.html << 'EOF'
          # <!DOCTYPE html>
          # <html lang="zh-CN">
          # <head><meta charset="UTF-8"><title>JSON Viewer</title></head>
          # <body><pre id="data">Loading…</pre>
          # <script>
          #   fetch('converted_data.json')
          #     .then(r => r.json())
          #     .then(d=>document.getElementById('data').textContent=JSON.stringify(d,null,2))
          #     .catch(e=>document.getElementById('data').textContent=e);
          # </script>
          # </body>
          # </html>
          # EOF

      # 4. 上传 artifact 供 Pages 使用
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

      # 5. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
