name: Update All Music Data

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  move-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mogai branch
        uses: actions/checkout@v3
        with:
          ref: mogai
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run convert.py
        run: python convert.py

      - name: Run intl_convert.py
        run: python intl_convert.py

      - name: Rename JSON file to avoid .gitignore issues
        run: mv convert_music_data.json converted_data.json

      - name: Rename JSON file to avoid .gitignore issues
        run: mv convert_intl_music_data.json converted_data_intl.json

      - name: Move JSON file to new branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git checkout convert-data 2>/dev/null || git checkout -b convert-data
          
          git add converted_data.json

          git add converted_data_intl.json
          
          git commit -m "Add converted_data.json generated by convert.py" || echo "No changes to commit"

          git commit -m "Add converted_data_intl.json generated by intl_convert.py" || echo "No changes to commit"
          
          git push origin HEAD:mogai-auto --force
